version: '2.2'

services:
  e-frame:
    image: registry.cn-hangzhou.aliyuncs.com/epet/epet_swoole:4.3.4-sdebug
    ports:
      - 7007:7007
    volumes:
      - /www/htdocs:/var/www
      - /wwwlogs:/wwwlogs
      - /home/smile/.ssh:/root/.ssh
    tty: true
    working_dir: /var/www/gott-trade-center
    command: php bin/server
    environment:
      #      - dockerhost=192.168.45.22
      - PHP_IDE_CONFIG=serverName=dockerhost
      - XDEBUG_CONFIG=remote_enable=1 remote_port=9001 remote_host=192.168.45.22 remote_connect_back=on idekey=PHPSTORM remote_handler=dbgp remote_autostart=1 remote_mode=req
      - ENVIRONMENT=local
#    network_mode: host
#    networks:
#      - host
#    dns:
#      - 8.8.8.8
#      - 114.114.114.114

